<?php $this->headTitle("Sign in"); ?> 
<section id="body_container">
    <!-- starts common container -->
    <section id="common_container">
       <?php echo $this->errMsg; ?> 

      <div class="curve"><img src="<?php echo $this->baseUrl(); ?>/img/common_t_curv.png" alt=""/></div>
      <?php if (isset ($this->messages)): ?>
      
      <?php foreach($this->messages as $msg): ?>
        <?php echo $msg; ?>
      <?php endforeach; ?>
      <?php endif; ?>
      <section class="common_content">
          <fieldset>
          <section class="sign_in_box">
            <div class="social_link"> <span class="icon1">
                    <a href="<?php echo $this->fblogin;?>"><img src="http://static.ak.fbcdn.net/rsrc.php/zB6N8/hash/4li2k73z.gif" /></a>
                </span> <small>or</small> </div>
             <?php echo $this->errorMessage; ?>
            <?php echo $this->loginForm; ?>
          </section>
          </fieldset>
      </section>
      <div class="curve"><img src="<?php echo $this->baseUrl(); ?>/img/common_b_curv.png" alt=""/></div>
      <!-- common container ends -->
    </section>
    <div class="sign_up_link"><img src="<?php echo $this->baseUrl(); ?>/img/green_left_curv.png" alt=""/><span>Need an account? <a href="<?php echo $this->baseUrl(); ?>/account/user/register">SIGN UP NOW</a></span><img src="<?php echo $this->baseUrl(); ?>/img/green_right_curv.png" alt=""/></div>
  </section>
  <!--body container ends-->

