
<?php echo $this->errors ?>
<br /><br />
<div id="view-content">
 
        <p>Ride requests for <?php echo $this->date; ?> !</p>

<?php if (count($this->requests) > 0): ?>
       <section class="passenger_results">
      <div class="head_section">
        <?php $final_dest = null ; ?>
        <?php if($this->where == "toAirport"): ?>
        <?php $final_dest = "DEPART FROM"; ?>
        <h3>Passengers needing rides to <?php echo $this->searchtitle; ?> on <?php echo $this->date; ?> </h3>
        <?php endif; ?>
        <?php if ($this->where == "fromAirport") :?>
         <?php $final_dest = "ARRIVE AT"; ?>
         <h3>Passengers needing rides from <?php echo $this->searchtitle; ?> on <?php echo $this->date; ?> </h3>
        <?php endif; ?>
        <ul>
          <li class="none">Sort by: </li>
          <li class="none"><a href="#">Distance </a></li>
          <li><a href="#">Price</a></li>
          <li><a href="#">Rating</a></li>
          <li class="active"><a href="#">Time</a></li>
        </ul>
      </div>
      <div class="passenger_content">
        <div class="col_head"><span class="col01">NAME</span> <span class="col02"><?php echo $final_dest; ?></span> <span class="col03">Depart time</span> <span class="col03">Duration</span> 
            <span class="col01">
             <?php if ($this->where == "fromAirport"):?>
                Distance from your destination
            <?php else: ?>
                Distance from your departure
            <?php endif;?>
            </span> </div>
          
         <?php  $this->date = str_replace("/", "-", $this->date); ?>
<?php foreach($this->requests as $request): ?>
    
        <?php $requestKey = $request['key'];
               //print_r($requestKey);
              $requestValue = $request['value'];
              $firstName = $requestKey['first_name'];
              $lastName = $requestKey['last_name'];
              $cost = $this->escape($requestKey['cost']);
              $departure_time = $this->escape($requestKey['departure_time']);
              $duration = $this->escape($requestKey['duration']);
        ?>
         
          
         <?php
        $details_url = $this->url(array(
            
            'module' => 'requests',
            'controller' => 'index',
            'action' => 'details',
            'where' => $this->where,
            'trip_id' => $requestKey['id'],
            'trip_date' => $this->date,
            'airport' => $this->searchtitle
            )
                 
      );
        
             $buy_now = array(
               
             'request_id' => $requestKey['id'],
             'publisher_id' => $requestKey['user_id'],
             'module' => 'requests',
             'controller' => 'index',
             'action' => 'offer',
             'request_open' => $requestKey['request_open'],
             'airport' => $this->searchtitle,
             'tripcost' => $requestKey['cost'],
             'where' => $this->where,
             'passengerEmail' => $requestKey['email'],
             "date" => $this->date,
             'passengerName' => $requestKey['first_name']  .  " " . $requestKey['last_name']
                 
              );
        $city = $requestKey['city'];
        if ($city == ""){
            $city = "unavailable";
        }
        ?>
        
       
   
        <div class="row">
          <div class="curve"><img src="<?php echo $this->baseUrl(); ?>/img/passenger_top.png" alt=""></div>
          <div class="text_area">
            <div class="col1"><img width="100px" height="100px" src="<?php echo $this->showpic(($requestKey['profile_pic'])); ?>" alt=""></div>
            <div class="col2">
              <p><?php echo $this->escape($firstName) . " " . $this->escape($lastName[0])."" ?></p>
              <small><img src="<?php echo $this->baseUrl(); ?>/img/rate.png" alt=""></small> </div>
            <div class="col3">
              <p class="head"><span><?php echo $this->escape($requestKey['city']); ?></span> <span><?php print( date("g:i a", strtotime($departure_time)) ); ?></span> 
                  <span><?php echo $duration; ?></span>
                  <span>
              
              <?php echo $this->escape($requestValue); ?>
                  
                  </span> </p>
              <p>
              <?php if ($this->where == "fromAirport"):?>
               I need to be  dropped  off at <?php echo $this->escape($requestKey['drop_off_address']); ?> </br>
             <?php else: ?>
              I need to be picked up from </b><?php echo $this->escape($requestKey['pick_up_address']); ?> </br>
            <?php endif; ?>
            </div>
            <div class="col4">
              <p><a target="_blank" href="<?php echo $details_url; ?>">Details</a></p>
            </div>
            <div class="col5"> <small>offering</small> <strong>$<?php echo $cost; ?></strong> <small></small> <span><?php echo $this->processrequestbooking($buy_now); ?></span> </div>
          </div>
          <div class="curve"><img src="<?php echo $this->baseUrl(); ?>/img/passenger_btm.png" alt=""></div>
        </div>
      
        
       
    
 <?php endforeach; ?>
  </div>
      </div>
    </section>
  <?php else : ?>
      <div class="head_section">
        <h3>No passengers found for <?php echo $this->date; ?></h3>
        <p></p>
        <a href="#" onclick="gotoPostRidePage()">Click here to post your ride so other passengers can contact you</a>
      </div>
   <?php endif; ?>
</div>

<script src="<?php echo $this->baseUrl(); ?>/js/booking.js"></script>