 <?php echo $this->headScript()->appendFile( $this->baseUrl() . '/js/jquery.slideto.js'); ?>

  <!--body container starts-->
  <section id="body_container"> 
    <!--home container starts-->
    <section id="home_container"> 
      <!--top head starts-->
      <div class="top_head">
        <h1>Connect. Share. Ride.</h1>
        <div class="tab">
          <ul>
            <li class="first"><a href="<?php echo $this->baseUrl();?>/index/passengersearch">I'm a passenger</a></li>
            <li class="second active"><a href="<?php echo $this->baseUrl();?>/index/driversearch">I'm a driver</a></li>
          </ul>
        </div>
      </div>
      <div class="tab_con">
      </div>
      <!--top head ends--> 
    </section>
    <!--home container ends--> 
  </section>
  <!--body container ends--> 
