   <div  class="content_details" >
        <div class="top"> 
          <!--left sec starts-->
          <div class="left_sec">
            <div class="top_row"> 
            <div class="radio_area"><span>Going to Airport</span>
              <input name="where" type="radio"  id ="where-toAirport"value="toAirport" class="radio">
              </div> 
            <div class="radio_area right"><span>Leaving Airport</span>
              <input name="where" type="radio" id ="where-fromAirport" value="fromAirport" class="radio">
              </div> 
            </div>
 
              <span class="row">
            <label>From</label>
            <input name="" id="departure" type="text" class="field" placeholder="Enter departure" >
            </span> <span class="row">
            <label>To</label>
            <input name="" id="destination" type="text" class="field" placeholder="Enter destination" >
            </span> <span class="row">
            <label>Date</label>
            <input name="" id="trip_date" type="text" class="field" placeholder="date">
            </span> 
<!--            <span class="row">
            <label>Time</label>
            <select  id = "trip_time" class="field">
            <option>anytime</option>
            <option>morning</option>
            <option>afternoon</option>
            <option>evening</option>
            </select>
            </span>-->
            </div>
          <!--left sec ends-->
          <div id="latest" class="latest_rides">
                
            </div>
          </div>
        </div>
      </div>
      <div class="bottom">
        <div class="bottom_tab">
          <ul>
            <li><input name="" type="button" id="findrides" onclick="findRides()" value="Find Drivers" /></li>
            <li><input name="" type="button" onclick ="gotoRequestRidePage()" id ="postride"value="Post Ride Request" /></li>
          </ul>
        </div>
      </div>
       <div id="results">
         
     </div>
  
<script type="text/javascript">
$(document).ready(function() {
  
    $("#trip_date").datepicker({"dateFormat":"mm/dd/yy","minDate":"0"});
});

  $(function() {
         $("#where-toAirport").click(function(){
           initializeDepartureAutocomplete();
            setAirportNameTripsToAirport("#departure", "#destination");
           $("#departure").attr('placeholder', "Enter your pickup address");
           $("#destination").attr('placeholder', "Enter airport name");
           $("#destination").val("Denver International Airport");
           $("#departure").autocomplete({"source": []});
           $("#destination").autocomplete({"source" : [<?php echo $this->airportList; ?>]});
           
         });
     }) ;
        
      $(function() {
         $("#where-fromAirport").click(function(){
           initializeDestinationAutocomplete();
            setAirportNameTripsFromAirport("#departure", "#destination");
            $("#departure").attr('placeholder', "Enter airport name");
           // $("#departure").autocomplete({"source":[{"key":2,"value":"Denver International airport"},{"key":3,"value":"Phoenix International Airport"}]});
           $("#destination").attr('placeholder', "Enter your drop-off address");
           $("#departure").autocomplete({"source" : [<?php echo $this->airportList; ?>]});
           $("#destination").autocomplete({"source" : []}); //Clears the other field
            
         });
     }) ;
     

</script>

