<script>
function gotoPostRidePage(){
    window.location = 'ride/index/post';
}
</script>

<script>
function reduceSeatByOne(){
    
    var num_seats = $("#numseats").html();
    num_seats = num_seats -1;
    $("#numseats").html(num_seats);
    
}
</script>
<?php 
$this->addHelperPath('ZendX/JQuery/View/Helper/', 'ZendX_JQuery_View_Helper');
echo $this->errors; 
?>

    <!-- results ends -->


<?php if (count($this->rides) > 0): ?>
       <section class="passenger_results">
      <div class="head_section">
        <?php $arrivalordestination = null; ?>
        <?php if($this->where == "toAirport"): ?>
          <?php $arrivalordestination = "DEPART FROM"; ?>
        <h3>Rides to <?php echo $this->searchtitle; ?> found for <?php echo $this->date; ?> </h3>
        <?php endif; ?>
        <?php if ($this->where == "fromAirport") :?>
         <?php $arrivalordestination = "ARRIVE AT"; ?>
         <h3>Rides from <?php echo $this->searchtitle; ?> found for <?php echo $this->date; ?> </h3>
        <?php endif; ?>
        <ul>
          <li class="none">Filter by: </li>
          <li class="none"><a href="#">Distance</a></li>
          <li><a href="#">Price</a></li>
          <li><a href="#">Rating</a></li>
          <li class="active"><a href="#">Time</a></li>
        </ul>
      </div>
      <div class="passenger_content">
        <div class="col_head"><span class="col01">NAME</span> <span class="col02"><?php echo $arrivalordestination; ?></span>

        <span class="col03">Depart time</span> 
        <span class="col03">EST ARRIVAL</span> 
            <span class="col01">
             <?php if ($this->where == "fromAirport"):?>
                Distance from your destination
            <?php else: ?>
                Distance from your departure
            <?php endif;?>
            </span> </div>
<?php foreach($this->rides as $ride): ?>
    
       <?php #print_r($ride); ?>
        <?php $rideKey = $ride['key'];
              $rideValue = $ride['value'];
              
              $firstName = $rideKey['first_name'];
              $lastName = $rideKey['last_name'];
              $cost = $this->escape($rideKey['cost']);
              $seat_num =  $this->escape($rideKey['number_of_seats']);
              $departure_time = $this->escape($rideKey['departure_time']);
              $arrival_time = $this->escape($rideKey['arrival_time']);

        ?>
        
   
        <div class="row">
          <div class="curve"><img src="<?php echo $this->baseUrl(); ?>/img/passenger_top.png" alt=""></div>
          <div class="text_area">
            <div class="col1"><img width="100px" height="100px" src="<?php echo $this->escape($rideKey['profile_pic']); ?>?type=large" alt=""></div>
            <div class="col2">
              <p><?php echo $this->escape($firstName) . " " . $this->escape($lastName[0])."" ?></p>
              <small><img src="<?php echo $this->baseUrl(); ?>/img/rate.png" alt=""></small> </div>
            <div class="col3">
              <p class="head"><span>Boulder</span> <span><?php print( date("g:i a", strtotime($departure_time)) ); ?></span> 
                  <span><?php print( date("g:i a", strtotime($arrival_time)) ); ?></span>
                  <span>
              
              <?php echo $this->escape($rideValue); ?>
                  
                  </span> </p>
              <p>
              <?php if ($this->where == "fromAirport"):?>
               I'll be dropping off at <?php echo $this->escape($rideKey['drop_off_address']); ?> </br>
             <?php else: ?>
              I'll be leaving from </b><?php echo $this->escape($rideKey['pick_up_address']); ?> </br>
            <?php endif; ?>
            </div>
            <div class="col4">
              <p><a href="#">Details</a></p>
            </div>
            <div class="col5"> <small><?php echo $seat_num; ?> seats</small> <strong>$<?php echo $cost; ?></strong> <small>each</small> <span><a href="#">Buy Now</a></span> </div>
          </div>
          <div class="curve"><img src="<?php echo $this->baseUrl(); ?>/img/passenger_btm.png" alt=""></div>
        </div>
      
   
<!--        <div id ="buyseat">   <?php 
        $driverName = $this->escape($rideKey['first_name']) . " " . $this->escape($rideKey['last_name']);
        $url =  $this->url(array(
             'module' => 'rides',
             'controller' => 'index',
             'action' => 'book',
             'trip_id' => $rideKey['id'],
             'publisher_id' => $rideKey['user_id'],
             'where' => $this->where,
             'driverEmail' => $rideKey['email'],
             'driverName' => $driverName
         ));
        echo  $this->ajaxLink("Buy Seat!",
                    "$url",
                    array(
                          'update' => '#buyseat',
                          'beforeSend' => 'slideup',
                           'complete' => 'reduceSeatByOne()'
                        )); 
        ?>
        </div>-->
        <p></p>
    
 <?php endforeach; ?>
    </div>
      </div>
    </section>
  <?php else : ?>
      <div class="head_section">
        <h3>No rides found for <?php echo $this->date; ?></h3>
        <p></p>
        <a href="#">Click here to post a ride request</a>
      </div>
   <?php endif; ?>
</div>
