<?php $this->headTitle("Add car profile"); ?>
<section id="body_container"> 
    <!--request_post container starts-->
    <section id="request_post_container">
      <div class="curve"><img src="<?php echo $this->baseUrl(); ?>/img/request_post_t_curv.png" alt=""/></div>
      <!-- request_post_details starts -->
      <section class="request_post_details">
       <?php echo $this->form; ?>
        <!-- request_post_details ends --></section>
      <div class="curve"><img src="<?php echo $this->baseUrl(); ?>/img/request_post_b_curv.png" alt=""/></div>
      <!--request_post container ends--></section>
  </section>
