<div id="view-content">
  <section id="body_container"> 
    <!--home container starts--> 
    <!-- starts common container -->
    <section id="common_container">
      <div class="curve"><img src="<?php echo $this->baseUrl(); ?>/img/common_t_curv.png" alt=""/></div>
      <section class="common_content">
          <h3>Please add a Paypal account before offering a ride. After adding your account, search and respond to passenger's request</h3>
        <?php echo $this->form; ?>
      </section>
     <div class="curve"><img src="<?php echo $this->baseUrl(); ?>/img/common_b_curv.png" alt=""/></div>
    </section>
  </section>
</div>
