<?php  $this->headTitle('How it works');
?>
<section id="body_container">
    <!-- about_container starts -->
    <section id="about_container">
      <div class="about_heading">
        <h3>How it works</h3>
      </div>
      <!-- about details starts -->
      <section class="about_details">
        <section class="howitworks_container">

<h3>Are you a Driver looking for passengers? </h3>
<h4>
Follow these simple three steps:
<ol>
    <li>From the homepage, select I am a driver and whether you are going to or leaving the airport</li> 
    <li>Enter your starting or ending address, date and time</li>
    <li>Select Find Passengers</li>
    </ol>

If you can’t find anyone traveling when you are, you can “post a ride offer” so passengers can find you
</h4>

<h3>Are you a Passenger looking for drivers? </h3>
<h4>
Follow these simple three steps:
<ol>
<li>From the homepage, select I am a passenger and whether you are going to or leaving the airport </li>
<li>Enter your starting or ending address, date and time</li>
<li>Select Find Drivers </li>
</ol>
If you cannot find anyone traveling when you need, you can “post a ride request” so drivers can find you.
</h4>


<div class="curve"><img src="<?php echo $this->baseUrl(); ?>/img/about_b_curv.png" alt=""/></div>
      <!-- about_container ends -->
    </section>
  </section>
    </section>
</section>