<section id="body_container">
    <!-- starts common container -->
    <section id="common_container">
      <div class="curve"><img src="<?php echo $this->baseUrl(); ?>/img/common_t_curv.png" alt=""/></div>
      <section class="common_content">
          <?php echo $this->errorMsg; ?>
          <?php echo $this->successMsg; ?>
          <fieldset>
          Please enter your email address
          <section class="sign_in_box">
            <?php echo $this->form; ?>
          </section>
          </fieldset>
      </section>
      <div class="curve"><img src="<?php echo $this->baseUrl(); ?>/img/common_b_curv.png" alt=""/></div>
      <!-- common container ends -->
    </section>
  </section>

