 <!--body container starts-->
 <?php $data = $this->data; 
  $name_abbv = $data['first_name'] . " ". $data['last_name'][0];
  //print_r($data);
  
   $buy_now = array(
               
             'request_id' => $data['id'],
             'user_id' => $data['user_id'],
             'module' => 'rides',
             'controller' => 'index',
             'tripcost' => $data['cost'],
             'request_open' => $data['request_open'],
             'action' => 'details',
             'airport' => $this->airport,
             'where' => $this->where,
             'passengerEmail' => $data['email'],
             'passengerName' => $data['first_name'] . " " . $data['last_name'],
             'publisher_id' => $data['user_id'],
             "date" => urlencode($this->trip_date),
             'driverName' => Zend_Auth::getInstance()->getIdentity()->first_name . " " . Zend_Auth::getInstance()->getIdentity()->last_name,
             'driverEmail' => Zend_Auth::getInstance()->getIdentity()->email                 
              );
 ?>
  <section id="body_container"> 
    <!-- details starts -->
    <div class="details_section">
      <div class="top_head">
        <h1>Community Ridesharing</h1>
      </div>
      <div class="curve"><img src="<?php echo $this->baseUrl(); ?>/img/home_top_bg.png" alt=""></div>
    <div class="detail_content">
        <h2>Details</h2>
        <!-- tab 1 -->
        <div class="tab_content1 tabing" style="display:none;">
          <div class="common_box">
            <div class="curve"><img src="<?php echo $this->baseUrl(); ?>/img/common_top.gif" alt=""></div>
            <div class="common_text"> <img width="264px" height="264px" src="<?php echo $this->showpic(urldecode($data['profile_pic'])); ?>" alt=""> </div>
            <div class="curve"><img src="<?php echo $this->baseUrl(); ?>/img/common_btm.gif" alt=""></div>
          </div>
          <div class="common_box">
            <div class="curve"><img src="<?php echo $this->baseUrl(); ?>/img/common_top.gif" alt=""></div>
            <div class="common_text">
              <h3><?php echo $this->escape($name_abbv); ?></h3>
              <p><span>City: </span><?php echo $this->escape($data['city']); ?></p>
              <p><span>State: </span><?php echo $this->escape($data['state']); ?></p>
              <p><span>Profession: </span><?php echo $this->escape($data['profession']); ?></p>
              <p><span>Age: </span><?php echo $this->escape($data['age']); ?></p>
            </div>
            <div class="curve"><img src="<?php echo $this->baseUrl(); ?>/img/common_btm.gif" alt=""></div>
          </div>
          <div class="common_box none">
            <div class="curve"><img src="<?php echo $this->baseUrl(); ?>/img/common_top.gif" alt=""></div>
            <div class="common_text"> &nbsp; </div>
            <div class="curve"><img src="<?php echo $this->baseUrl(); ?>/img/common_btm.gif" alt=""></div>
          </div>
        </div>
        <!-- tab 1 ends --> 
        
        
        
        <!-- tab 3 -->
        <div class="tab_content3 tabing" style="display:block;">
          <div class="common_box">
            <div class="curve"><img src="<?php echo $this->baseUrl(); ?>/img/common_top.gif" alt=""></div>
            <div class="common_text">
              <h3>TRIP INFO</h3>
              <p><span>City: </span><?php echo $this->escape($data['city']); ?></p>
              <p><span>Needs ride from: </span><em>
                 <?php if ($this->where == "toAirport"): ?>
                    <?php echo $this->escape($data['pick_up_address']); ?>
                   <?php elseif ($this->where == "fromAirport"): ?>
                    <?php echo $this->escape($this->airport); ?>
                    <?php endif; ?>   
                      </em></p>
              <p><span>Going to: </span>
                   <?php if ($this->where == "toAirport"): ?>
                    <em><?php echo $this->escape($this->airport); ?></em>
                   <?php elseif ($this->where == "fromAirport"): ?>
                    <em><?php echo $this->escape($data['drop_off_address']); ?></em>
                    <?php endif; ?>
                  </p>
                   
              <p><span>Date: </span><em><?php echo $this->escape(urldecode($this->trip_date)); ?></em></p>
              <p><span>Departure Time: </span><em><?php  print( date("g:i a", strtotime($this->escape($data['departure_time'])) )); ?></em></p>
              <p><span>Trip Duration: </span><em><?php echo $this->escape($data['duration']); ?></em></p>
              <p><span>Request message: </span><em><?php echo $this->escape($data['request_msg']); ?></em></p>
            </div>
            <div class="curve"><img src="<?php echo $this->baseUrl(); ?>/img/common_btm.gif" alt=""></div>
          </div>
          <div class="common_box">
            <div class="curve"><img src="<?php echo $this->baseUrl(); ?>/img/common_top.gif" alt=""></div>
            <div class="common_text">
              <h3>&nbsp;</h3>
              <p><span>Offering: </span><em>$<?php echo $this->escape($data['cost']); ?></em></p>
              <p><span>Luggage: </span><em>I have<br>
                <?php echo $this->escape($data['num_luggages']); ?> bag(s)</em></p>
              <p><span>Giving this person a trip saves: </span><em><?php echo $this->escape($data['emissions']); ?> kg of CO2</em></p>
            </div>
            <div class="curve"><img src="<?php echo $this->baseUrl(); ?>/img/common_btm.gif" alt=""></div>
          </div>
          <div class="common_box none">
            <div class="common_text none"><?php echo $this->processrequestbooking($buy_now); ?> </div>
          </div>
        </div>
        <!-- tab 3 ends --> 
        <!-- tab 4 -->
        <div class="tab_content4 tabing" style="display:none;">
          <div class="common_box review">
            <div class="curve"><img src="<?php echo $this->baseUrl(); ?>/img/review_top.gif" alt=""></div>
            <div class="common_text">
              <h3>REVIEW</h3>
              <ul class="rev">
                <li>
                  <div class="col1"><img src="<?php echo $this->baseUrl(); ?>/img/photo1.png" alt=""></div>
                  <div class="col2">Charlie</div>
                  <div class="col3">
                    <p>This is a gripping journey into the life of an amazing individual. Despite its girth of nearly 600 pages, the book zips along at a torrid pace.</p>
                    <img src="<?php echo $this->baseUrl(); ?>/img/rate.png" alt=""> </div>
                </li>
                <li>
                  <div class="col1"><img src="<?php echo $this->baseUrl(); ?>/img/photo1.png" alt=""></div>
                  <div class="col2">Melanie</div>
                  <div class="col3">
                    <p>The interviews with Jobs are fascinating and revealing. We get a real sense for what it must have been like to be Steve, or to work with him. That earns the book five stars despite its flaws, in that it's definitely a must-read if you have any interest at all in the subject.</p>
                    <img src="<?php echo $this->baseUrl(); ?>/img/rate.png" alt=""> </div>
                </li>
                <li>
                  <div class="col1"><img src="<?php echo $this->baseUrl(); ?>/img/photo1.png" alt=""></div>
                  <div class="col2">Charlie</div>
                  <div class="col3">
                    <p>This is a gripping journey into the life of an amazing individual. Despite its girth of nearly 600 pages, the book zips along at a torrid pace.</p>
                    <img src="<?php echo $this->baseUrl(); ?>/img/rate.png" alt=""> </div>
                </li>
              </ul>
            </div>
            <div class="curve"><img src="<?php echo $this->baseUrl(); ?>/img/review_btm.gif" alt=""></div>
          </div>
        </div>
        <!-- tab 4 ends --> 
        <!-- tab 5 -->
        <div class="tab_content5 tabing" style="display:none;">
          <div id="fb-root"></div>
          <div class="fb-comments" data-href="<?php echo $this->contact_url; ?>" data-num-posts="4" data-width="470"></div>
        </div>
        <!-- tab 5 ends --> 
        
      </div>
      <div class="bottom_tab_area"> 
       <ul class="tab">
          <li class="first"><a href=".tab_content1"><?php echo $name_abbv; ?></a></li>
           <?php if ($this->show_contact == "true"): ?>
          <li><a href=".tab_content3">Trip Info</a></li>
          <li class="active"><a href=".tab_content5 ">Contact</a></li>
          <script>
           $(".tabing").hide();
           $(".tab_content5").show();
          </script>
          <?php else: ?>
          <li class="active"><a href=".tab_content3">Trip Info</a></li>
          <li><a href=".tab_content5 ">Contact</a></li>
          <?php endif; ?>
          <li id ="tab_content4"><a href=".tab_content4">Review</a></li>
        </ul>
      </div>
    </div>
    <!-- details ends --> 
  </section>
  <!--body container ends-->
  
  <script src="<?php echo $this->baseUrl(); ?>/js/booking.js"></script>