<section id="body_container">
    <!-- about_container starts -->
    <section id="about_container">
      <div class="about_heading">
      </div>
   
<section class="about_details">
        <section class="about_details_1">
          <section class="about_content">
            <h4>Abdoul Gobitaka</h4>
            <span>Co-founder &amp; CFO</span>
            <p>
      Upon graduation, Abdoul moved to Boulder, Colorado to work on what he trully believes will change the way we commute. And through rideorama’s platform, Abdoul hopes to achieve that noble goal. 

In his spare time, Abdoul enjoys reading tech blogs and soccer news. He  is an avid soccer player and also watches European major soccer leagues.

Abdoul obtained his Associate Degree from Monroe College and Bachelors in Finance & Investment from City University of New York, Baruch College. Abdoul is also a member of lifttogo.org
            </p>
          </section>
          <div class="about_pic"><img src="<?php echo $this->baseUrl(); ?>/img/about_pic.jpg" alt=""/></div>
        </section>
        <!-- about details ends -->
      </section>
      <div class="curve"><img src="<?php echo $this->baseUrl(); ?>/img/about_b_curv.png" alt=""/></div>
      <!-- about_container ends -->
    </section>
  </section>