<?php  $this->headTitle('Abdul Gobitaka'); ?>
<section id="body_container">
    <!-- about_container starts -->
    <section id="about_container">
      <div class="about_heading">
      </div>
   
<section class="about_details">
        <section class="about_details_1">
          <section class="about_content">
            <h4>Abdoul Gobitaka</h4>
            <span>Co-founder &amp; Community Manager</span>
            <p>
    After emigrating from Togo, Abdoul put himself through College by driving a taxi in New York City.  He noticed how empty cars were when traveling to and from airports. He sees Rideorama as the solution to this problem and believes this platform will change the way we commute. 

    <br></br>In his spare time, Abdoul enjoys reading tech blogs and sports news. He is an avid soccer player and is fanatically dedicated to Real Madrid. Abdoul obtained his Bachelors in Finance & Investments from Baruch College. He is also a co-founder of LiftTogo.org, an organization that provides books and school supplies to underprivileged children in Togo.
     </p>
          </section>
          <div class="about_pic"><img src="<?php echo $this->baseUrl(); ?>/img/AbdulLarge.jpg" alt=""/></div>
        </section>
        <!-- about details ends -->
      </section>
      <div class="curve"><img src="<?php echo $this->baseUrl(); ?>/img/about_b_curv.png" alt=""/></div>
      <!-- about_container ends -->
    </section>
  </section>