<section id="body_container">
    <!-- about_container starts -->
    <section id="about_container">
      <div class="about_heading">
      </div>
    
<section class="about_details">
        <section class="about_details_1">
          <section class="about_content">
            <h4>Casey George</h4>
            <span>Co-founder &amp; CEO</span>
            <p>
            Casey received his BS in Chemical Engineering from Howard University and graduated with his MBA from Columbia Business School.
            </p>
          </section>
          <div class="about_pic"><img src="<?php echo $this->baseUrl(); ?>/img/about_pic.jpg" alt=""/></div>
        </section>
        <!-- about details ends -->
      </section>
      <div class="curve"><img src="<?php echo $this->baseUrl(); ?>/img/about_b_curv.png" alt=""/></div>
      <!-- about_container ends -->
    </section>
  </section>