<?php  $this->headTitle('Casey George'); ?>
<section id="body_container">
    <!-- about_container starts -->
    <section id="about_container">
      <div class="about_heading">
      </div>
    
<section class="about_details">
        <section class="about_details_1">
          <section class="about_content">
            <h4>Casey George</h4>
            <span>Co-founder &amp; CEO</span>
            <p>
                After working for four years as a Chemical Engineer, Casey decided to go back to business school to turn his hobby of investing into his profession.  Along the way, he fell in love with startups and is applying what he's learned about investing to entrepreneurship.  He loves analyzing markets and sees ridesharing as an efficient, practical, and overlooked opportunity that will greatly impact peoples' lives.  <br></br>He loves NFL football, playing the piano, good bourbon, and West Indian cuisine.  If you want the best curry you've ever tasted, just let him know! Casey graduated from Howard University with his Bachelors in Chemical Engineering and he received his MBA from Columbia Business School.
            </p>
          </section>
          <div class="about_pic"><img src="<?php echo $this->baseUrl(); ?>/img/CaseyLarge.jpg" alt=""/></div>
        </section>
        <!-- about details ends -->
      </section>
      <div class="curve"><img src="<?php echo $this->baseUrl(); ?>/img/about_b_curv.png" alt=""/></div>
      <!-- about_container ends -->
    </section>
  </section>