 <section id="body_container">
    <!-- about_container starts -->
    <section id="about_container">
      <div class="about_heading">
        <h3>About Us</h3>
      </div>
      <!-- about details starts -->
      <section class="about_details">
        <p>Getting to the airport is a pain.  Buses are slow, taxis and parking at the airport are expensive, and shared-ride vans are both.  People are left to choose between the least painful of terrible solutions.  That’s why almost 75% of trips to the airport in the US are done by cars.  Unfortunately, every five cars going to the airport only contain six people; tons of wasted space.  </p>
        <p> Ridesharing can reduce carbon emissions as well as the number of cars on the road.  That’s why we created Rideorama.  Our platform matches drivers going to and from the airport with passengers.  Drivers offset their costs. Passengers get cheap and direct travel. Rideorama makes airport ground access more convenient and more efficient simultaneously. </p>
        <section class="team_container">
          <h3>Rideorama team</h3>
          <section class="team_box">
            <div class="curve"><img src="<?php echo $this->baseUrl(); ?>/img/team_box_t_curv.gif" alt=""/></div>
            <section class="team_details"><a href="<?php echo $this->baseUrl();?>/aboutus/cgeorge"> <span class="image_box"><img src="<?php echo $this->baseUrl(); ?>/img/CaseySmall.jpg" alt=""/></span></a>
              <div class="image_details"> <strong>Casey George</strong> <span>Co-founder &amp; CEO</span> </div>
            </section>
            <div class="curve"><img src="<?php echo $this->baseUrl(); ?>/img/team_box_b_curv.gif" alt=""/></div>
          </section>
          <section class="team_box">
            <div class="curve"><img src="<?php echo $this->baseUrl(); ?>/img/team_box_t_curv.gif" alt=""/></div>
            <section class="team_details"><a href="<?php echo $this->baseUrl();?>/aboutus/agobitaka"> <span class="image_box"><img src="<?php echo $this->baseUrl(); ?>/img/AbdulSmall.jpg" alt=""/></span></a>
              <div class="image_details"> <strong>Abdoul Gobitaka</strong> <span>Co-founder &amp; Community Manager</span> </div>
            </section>
            <div class="curve"><img src="<?php echo $this->baseUrl(); ?>/img/team_box_b_curv.gif" alt=""/></div>
          </section>
          <section class="team_box">
            <div class="curve"><img src="<?php echo $this->baseUrl(); ?>/img/team_box_t_curv.gif" alt=""/></div>
            <section class="team_details"><a href="<?php echo $this->baseUrl();?>/aboutus/odibie"> <span class="image_box"><img src="<?php echo $this->baseUrl(); ?>/img/OvoSmall.jpg" alt=""/></span></a>
              <div class="image_details"> <strong>Ogheneovo (Ovo) Dibie</strong> <span>Co-founder &amp; CTO</span> </div>
            </section>
            <div class="curve"><img src="<?php echo $this->baseUrl(); ?>/img/team_box_b_curv.gif" alt=""/></div>
          </section>
          <section class="team_box last">
            <div class="curve"><img src="<?php echo $this->baseUrl(); ?>/img/team_box_t_curv.gif" alt=""/></div>
            <section class="team_details"><a href="<?php echo $this->baseUrl();?>/aboutus/ksabi"> <span class="image_box"><img src="<?php echo $this->baseUrl(); ?>/img/KamalSmall.jpg" alt=""/></span></a>
              <div class="image_details"> <strong>Kamal Sabi</strong> <span>Co-founder &amp; Community Manager</span> </div>
            </section>
            <div class="curve"><img src="<?php echo $this->baseUrl(); ?>/img/team_box_b_curv.gif" alt=""/></div>
          </section>
        </section>
        <!-- about details ends -->
      </section>
      <div class="curve"><img src="<?php echo $this->baseUrl(); ?>/img/about_b_curv.png" alt=""/></div>
      <!-- about_container ends -->
    </section>
  </section>