 <section id="body_container">
    <!-- about_container starts -->
    <section id="about_container">
      <div class="about_heading">
        <h3>About Us</h3>
      </div>
      <!-- about details starts -->
      <section class="about_details">
        <p>Driving alone in your car is expensive, boring and not so eco-friendly. Rideorama is a ridesharing marketplace focused on the airport ground access market that monetizes empty seats in drivers' cars through our easy to use web  application. Our Matching Marketplace, Ridesharer Profiles, and Payment Platform enable our users to find rideshare partners, build personal brands and engage in safe, reliable transactions.  </p>
        <p> The benefits of using rideorama are many.<br/>
          Sign up is free and simple.<br/>
          Save money on your commute.<br/>
          Make new friends<br/>
          Finally, by driving less you'll be helping to keep the air clean.<br/>
          There are more reasons that we can put in here </p>
        <section class="team_container">
          <h3>Rideorama team</h3>
          <section class="team_box">
            <div class="curve"><img src="<?php echo $this->baseUrl(); ?>/img/team_box_t_curv.gif" alt=""/></div>
            <section class="team_details"><a href="<?php echo $this->baseUrl();?>/aboutus/cgeorge"> <span class="image_box"><img src="<?php echo $this->baseUrl(); ?>/img/team_pic1.jpg" alt=""/></span></a>
              <div class="image_details"> <strong>Casey George</strong> <span>Co-founder &amp; CEO</span> </div>
            </section>
            <div class="curve"><img src="<?php echo $this->baseUrl(); ?>/img/team_box_b_curv.gif" alt=""/></div>
          </section>
          <section class="team_box">
            <div class="curve"><img src="<?php echo $this->baseUrl(); ?>/img/team_box_t_curv.gif" alt=""/></div>
            <section class="team_details"><a href="<?php echo $this->baseUrl();?>/aboutus/agobitaka"> <span class="image_box"><img src="<?php echo $this->baseUrl(); ?>/img/team_pic2.jpg" alt=""/></span></a>
              <div class="image_details"> <strong>Abdoul Gobitaka</strong> <span>Co-founder &amp; CFO</span> </div>
            </section>
            <div class="curve"><img src="<?php echo $this->baseUrl(); ?>/img/team_box_b_curv.gif" alt=""/></div>
          </section>
          <section class="team_box">
            <div class="curve"><img src="<?php echo $this->baseUrl(); ?>/img/team_box_t_curv.gif" alt=""/></div>
            <section class="team_details"><a href="<?php echo $this->baseUrl();?>/aboutus/odibie"> <span class="image_box"><img src="<?php echo $this->baseUrl(); ?>/img/team_pic3.jpg" alt=""/></span></a>
              <div class="image_details"> <strong>Ogheneovo (Ovo) Dibie</strong> <span>Co-founder &amp; CTO</span> </div>
            </section>
            <div class="curve"><img src="<?php echo $this->baseUrl(); ?>/img/team_box_b_curv.gif" alt=""/></div>
          </section>
          <section class="team_box last">
            <div class="curve"><img src="<?php echo $this->baseUrl(); ?>/img/team_box_t_curv.gif" alt=""/></div>
            <section class="team_details"><a href="<?php echo $this->baseUrl();?>/aboutus/ksabi"> <span class="image_box"><img src="<?php echo $this->baseUrl(); ?>/img/team_pic3.jpg" alt=""/></span></a>
              <div class="image_details"> <strong>Kamal Sabi</strong> <span>Co-founder &amp; COO</span> </div>
            </section>
            <div class="curve"><img src="<?php echo $this->baseUrl(); ?>/img/team_box_b_curv.gif" alt=""/></div>
          </section>
        </section>
        <!-- about details ends -->
      </section>
      <div class="curve"><img src="<?php echo $this->baseUrl(); ?>/img/about_b_curv.png" alt=""/></div>
      <!-- about_container ends -->
    </section>
  </section>