<section id="body_container">
    <!-- about_container starts -->
    <section id="about_container">
      <div class="about_heading">
      </div>
   
<section class="about_details">
        <section class="about_details_1">
          <section class="about_content">
            <h4>Kamal Sabi</h4>
            <span>Co-founder &amp; Community Manager</span>
            <p>
             A year ago, Kamal took a break from earning his Masters at CU to visit Germany and France with family.  During his stay, he took advantage of the vast ridesharing network Europe had to offer.  Ridesharing made perfect sense to him--it brought back memories of his upbringing in Togo where the community shared resources.  He wondered why this fun, sensible way of commuting hadn't taken hold in the US and decided to do something about it.   
            <br></br>When he is not working, he enjoys polishing his cooking skills. He’s a Food Network fanatic, and Iron Chef America is his favorite show. Kamal received his Bachelors and Masters in Electrical Engineering from the University of Colorado, Boulder. He is also a co-founder of LiftTogo.org, an organization that provides books and school supplies to underprivileged children in Togo .

               </p>
          </section>
          <div class="about_pic"><img src="<?php echo $this->baseUrl(); ?>/img/KamalLarge.jpg" alt=""/></div>
        </section>
        <!-- about details ends -->
      </section>
      <div class="curve"><img src="<?php echo $this->baseUrl(); ?>/img/about_b_curv.png" alt=""/></div>
      <!-- about_container ends -->
    </section>
  </section>