<section id="body_container">
    <!-- about_container starts -->
    <section id="about_container">
      <div class="about_heading">
      </div>
   
<section class="about_details">
        <section class="about_details_1">
          <section class="about_content">
            <h4>Kamal Sabi</h4>
            <span>Co-founder &amp; COO</span>
            <p>
            Kamal was once given a ride by a stranger who soon became his friend while he was waiting to catch a cab in the apple city from LaGuardia Airport to John F. Kennedy international Airport. This warm and fun experience changed how he views the world; he thinks that we can be more efficient within our society and help one another by sharing resources. 
When he is not working, he volunteers his time to help impoverished kids have access to a better education. Kamal received his Masters in Electrical Engineering from the University of Colorado at Boulder
               </p>
          </section>
          <div class="about_pic"><img src="<?php echo $this->baseUrl(); ?>/img/about_pic.jpg" alt=""/></div>
        </section>
        <!-- about details ends -->
      </section>
      <div class="curve"><img src="<?php echo $this->baseUrl(); ?>/img/about_b_curv.png" alt=""/></div>
      <!-- about_container ends -->
    </section>
  </section>