<section id="body_container">
    <!-- about_container starts -->
    <section id="about_container">
      <div class="about_heading">
      </div>
   

<section class="about_details">
        <section class="about_details_1">
          <section class="about_content">
            <h4>Ogheneovo (Ovo) Dibie</h4>
            <span>Co-founder &amp; CTO</span>
            <p>As a loyal fan of  Manchester City FC and soccer aficionado, Ovo feels everything including the way we travel should be as beautiful as the beautiful game. <br></br> He cringes at the huge environmental foot print of single passenger vehicles criss-crossing mother earth and believes we can reduce this impact one ride share at a time. If Ovo ever made it to American Idol, I'm sure 'Save an ozone ride with someone' would be his special number. Ovo is currently a graduate student in Computer Science at the University of Colorado Boulder.</p>
          </section>
          <div class="about_pic"><img src="<?php echo $this->baseUrl(); ?>/img/OvoLarge.jpg" alt=""/></div>
        </section>
        <!-- about details ends -->
      </section>
      <div class="curve"><img src="<?php echo $this->baseUrl(); ?>/img/about_b_curv.png" alt=""/></div>
      <!-- about_container ends -->
    </section>
  </section>