<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8"></meta>    
        <meta name="viewport" content="initial-scale=1.0, user-scalable=no" />
        <script src="http://maps.googleapis.com/maps/api/js?sensor=false&libraries=places"></script>

 <?php 
        
        echo $this->headTitle("Rideorama");
        
        
        echo $this->headLink()->appendStylesheet($this->baseUrl(). '/css/smoothness/jquery.css');
            echo $this->jQuery()
                     ->setVersion('1.6.2')
                     ->setUIVersion('1.8.14');
   ?>
   
    <script>
     function initialize() {
        var input = document.getElementById('departure');
        var autocomplete = new google.maps.places.Autocomplete(input);
       // var autocompleteHomepage = new google.maps.places.Autom
     }
     google.maps.event.addDomListener(window, 'load', initialize);
    </script>
    <style type="text/css">
  html { height: 100% }
  body { height: 100%; margin: 0; padding: 0 }
  #departure { width: 350px}
  #map_canvas { height: 100% }
</style>
    </head>
    <div id="content">
<?php echo $this->layout()->content; ?>
    </div>
    
    <div id ="fotter">
        &copy 2011 Rideorama
    </div>
</html>