<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8"></meta>
        <meta name ="description" content="Rideorama is a community driven marketplace for ridesharing to and from airports. If you're a 
        driver going to the airport, you can list extra seats in your car and as a passenger you can request a ride so other drivers can find you" />
        
       <meta name ="keywords" content="rides, ridesharing, carpooling, carpool, airport ride, airport, share, travel, rideorama" />
        <meta property="og:title" content="Rideorama" />
        <meta property="og:type" content="company" />
        <meta property="og:url" content="http://www.rideorama.com" />
        <meta property="og:image" content="http://rideorama.com/favicon.ico" />
        <meta property="og:site_name" content="Rideorama" />
        <meta property="fb:admins" content="193300995" />
        <meta name="viewport" content = "width=device-width ,  user-scalable=no">
        <script src="http://maps.googleapis.com/maps/api/js?sensor=false&libraries=places"></script>
        <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.6.2/jquery.min.js"></script>
        <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.14/jquery-ui.min.js"></script>
        <link href="<?php echo $this->baseUrl(); ?>/jqtransformplugin/jqtransform.css" rel="stylesheet" type="text/css"  />
        <script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/js/cufon-yui.js"></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/js/Helvetica_700.font.js"></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/js/cufon.js"></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/js/indextabs.js"></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/jqtransformplugin/jquery.jqtransform.js"></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/js/jcarousellite_1.0.1.js"></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl();?>/js/tabs2.js"></script>

 <?php
        
       echo $this->jQuery()
                    ->setVersion('1.6.2')
                     ->setUIVersion('1.8.14');
       $this->headTitle()->setSeparator(' | ');
       echo $this->headTitle("Rideorama");
       echo $this->headTitle();
        echo $this->headLink()->appendStylesheet($this->baseUrl(). '/css/smoothness/jquery-ui.css');
       echo $this->headLink()->prependStylesheet($this->baseUrl() . '/css/style.css');
   ?>
   
<meta name="description=" content="Rideorama is a ridesharing marketplace focused on airports.
 We match drivers and passengers who are going to and from airports">

      </head>
      <body>
          <script>
window.fbAsyncInit = function() {
    FB.init({
      appId      : '193300995', // App ID
    channelUrl : 'http://localhost/rideorama/public/channel.html', // Channel File
      status     : true, // check login status
      cookie     : true, // enable cookies to allow the server to access the session
      xfbml      : true  // parse XFBML
    });

    // Additional initialization code here
  };   
   
   (function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/en_GB/all.js#xfbml=1&appId=370456989661142";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));
</script>
 <div id ="wrapper">
    <?php
    $logged_in_user = null;
    if (Zend_Auth::getInstance()->hasIdentity()){
        $logged_in_user = Zend_Auth::getInstance()->getIdentity()->first_name . " " . Zend_Auth::getInstance()->getIdentity()->last_name;
    }
    ?>
       <header> <a href="<?php echo $this->baseUrl(); ?>"><img src="<?php echo $this->baseUrl();?>/img/logo.png" alt="" class="logo" /></a>
    <nav class="top_nav">
      <ul>
       <li class="none"> <a href="<?php echo $this->baseUrl(); ?>/account/user">
      <?php echo $logged_in_user; ?>&nbsp;</a></li>
      <?php echo $this->navigation(); ?>
      </ul>
    </nav>
  </header>

     <div id="content">
        <?php echo $this->layout()->content; ?>
         
     </div>
     <div id="fb-root"></div>

    <footer>
          <ul>
      <li><a href="<?php echo $this->baseUrl();?>/aboutus">About us</a></li>
      <li><a href="<?php echo $this->baseUrl();?>/privacy">Privacy</a></li>
      <li><a href="<?php echo $this->baseUrl();?>/terms">Terms and Conditions</a></li>
      <li><a href="<?php echo $this->baseUrl();?>/howitworks">How it works</a></li>
    
      <li><a href="<?php echo $this->baseUrl();?>/faqs">FAQS</a></li>
      <li> <span class="icons"> 
           <a target="_blank"href="http://twitter.com/Rideorama"><img src="<?php echo $this->baseUrl();?>/img/social_icon2.gif" alt="" /></a></span> 
             <a target="_blank" href="https://www.facebook.com/pages/Rideorama/201052663306856"><img src="<?php echo $this->baseUrl();?>/img/social_icon1.gif" alt="" /></a>
             </span></li>
              <li><span class="icons">
                   <fb:like href="http://www.rideorama.com" send="false" width="400" show_faces="false"></fb:like>
  
                  </span>
               
               <p class="footer"><?php echo $this->footer(); ?></p>

          </ul>
    
    </footer>
   
     

 </body>
 <script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/js/jquery.slideto.js"></script>
 <script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/js/homepage.js"></script>
<script src="<?php echo $this->baseUrl();?>/media/js/jquery.dataTables.min.js"></script>
<link href="<?php echo $this->baseUrl();?>/media/css/jquery.dataTables.css" media="screen" rel="stylesheet" type="text/css">
 <script>
     $(document).ready(function(){
    $(this).scrollTop(0);
});
 </script>
</html>