<?php $this->headTitle("Post trip"); ?>
<section id="body_container"> 
    <!--request_post container starts-->
    <section id="request_post_container">
      <div class="curve"><img src="<?php echo $this->baseUrl(); ?>/img/request_post_t_curv.png" alt=""/></div>
      <!-- request_post_details starts -->
      <section class="request_post_details">
      <?php echo $this->msg; ?>
       <?php echo $this->form; ?>
        <!-- request_post_details ends --></section>
      <div class="curve"><img src="<?php echo $this->baseUrl(); ?>/img/request_post_b_curv.png" alt=""/></div>
      <!--request_post container ends--></section>
  </section>

<?php if ($this->where == "toAirport"): ?>
<script>
  function setDepartureAutoComplete(){
      var input = document.getElementById('departure');
      var autocomplete = new google.maps.places.Autocomplete(input);
     }
     google.maps.event.addDomListener(window, 'load', setDepartureAutoComplete)  
</script>
<?php endif; ?>

<?php if ($this->where == "fromAirport"): ?>
<script>
     function setDestinationAutoComplete(){
      var input = document.getElementById('destination');
      var autocomplete = new google.maps.places.Autocomplete(input);
     }
     google.maps.event.addDomListener(window, 'load', setDestinationAutoComplete);
 </script>
<?php endif; ?>
 <?php echo $this->headScript()->appendFile($this->baseUrl() . "/js/validateform.js"); ?>
  <?php echo $this->headScript()->appendFile($this->baseUrl() . "/js/jquery-ui-timepicker-addon.js"); ?>
<script>
      $('#trip_time').timepicker({
	ampm: true,
	hourMin: 0,
        stepMinute: 15,
	hourMax: 24
        
});
          
 </script>


