<br /><br />
<div id="view-content">
	<p>View script for controller <b>Index</b> and script/action name <b>post</b></p>
        <?php echo $this->msg; ?>
</div>
<?php echo $this->form; ?>

<?php if ($this->where == "toAirport"): ?>
<script>
  function setDepartureAutoComplete(){
      var input = document.getElementById('departure');
      var autocomplete = new google.maps.places.Autocomplete(input);
     }
     google.maps.event.addDomListener(window, 'load', setDepartureAutoComplete)  
</script>
<?php endif; ?>

<?php if ($this->where == "fromAirport"): ?>
<script>
     function setDestinationAutoComplete(){
      var input = document.getElementById('destination');
      var autocomplete = new google.maps.places.Autocomplete(input);
     }
     google.maps.event.addDomListener(window, 'load', setDestinationAutoComplete);
 </script>
<?php endif; ?>
 <?php echo $this->headScript()->appendFile($this->baseUrl() . "/js/validateform.js"); ?>
