<div id="action"></div>

<?php if(empty($this->myrides) && empty($this->ridesBookedToAirport) && empty($this->ridesBookedFromAirport)
    && empty($this->requestsToAirportResponded) && empty($this->requestsFromAirportResponded)): ?>

You have currently have no rides

<?php else: ?>
          <table id="rides">
            <thead>
              <tr>
                <th>DATE</th>
                <th>FROM</th>
                <th>TO</th>
                <th>STATUS</th>
                <th>COST</th>
                <th>WHO WITH</th>
                <th>Edit</th>
                <th>Delete</th>
              </tr>
            </thead>
            <?php 
            $fromAirport = $this->myrides[0]['ridesfromairport']; // Rides given as driver from airport
            $toAirport = $this->myrides[1]['ridestoairport']; // Rides given as driver to airprot
            $requestFromAirport = $this->myrides[2]['requestsfromairport']; //Requests made as a passenger from the airport
            $requestToAirport = $this->myrides[3]['requeststoairport']; // Requests made to the airport
            $ridesBookedToAirport =  $this->ridesBookedToAirport; // Rides I booked a seat as a passenger to airport
            $ridesBookedFromAirport =  $this->ridesBookedFromAirport; // Rides I booked a seat as a passenger from airport
            $requestsToAirportResponded = $this->requestsToAirportResponded; // Requests to airport that were fulfilled as a driver
            $requestsFromAirportResponded = $this->requestsFromAirportResponded; //Requests from airport that were fulfilled as a driver
            ?>
                        <tbody>

             <?php foreach($fromAirport as $r): ?>
              <tr id="<?php echo $r['id']; ?>">
                <td><?php echo $this->showdate($r['departure_date']); ?> </td>
                <td><?php echo $r['iata']; ?></td>
                <td><?php echo $r['city']; ?></td>
                <td>Driver</td>
                <td>$<?php echo $r['cost']; ?></td>
                <td><a id="withwho"  onclick="getUsers('<?php echo $this->showmembers("driver", $r['departure_date']); ?>');" href="javascript:void(0)">Click to View</a></td>
                <td><?php echo $this->showedit($r, "rides", "fromAirport"); ?></td>
                <td><?php echo $this->showdelete($r, "rides", "fromAirport"); ?></td>
              </tr>
            <?php endforeach; ?>
            
            <?php foreach($toAirport as $r): ?>
              <tr id="<?php echo $r['id']; ?>">
                <td><?php echo $this->showdate($r['departure_date']); ?> </td>
                <td><?php echo $r['city']; ?></td>
                <td><?php echo $r['iata']; ?></td>
                <td>Driver</td>
                <td>$<?php echo $r['cost']; ?></td>
                <td><a id="withwho" onclick="getUsers('<?php echo $this->showmembers("driver", $r['departure_date']); ?>');" href="javascript:void(0)">Click to View</a></td>
                <td><?php echo $this->showedit($r, "rides", "toAirport"); ?></td>
                <td><?php echo $this->showdelete($r, "rides", "toAirport"); ?></td>
              </tr>
            <?php endforeach; ?>
          
            
            <?php foreach($requestFromAirport as $r): ?>
              <tr id="<?php echo $r['id']; ?>">
                <td><?php echo $this->showdate($r['departure_date']); ?> </td>
                <td><?php echo $r['iata']; ?></td>
                <td><?php echo $r['city']; ?></td>
                <td>Passenger</td>
                <td>$<?php echo $r['cost']; ?></td>
                <td><a id="withwho" href="javascript:void(0)" onclick="getUsers(<?php echo $this->showmembers("passenger",$r['departure_date']); ?>);">Click to View</a></td>
                <td><?php echo $this->showedit($r, "requests", "fromAirport"); ?></td>
                <td><?php echo $this->showdelete($r, "requests", "fromAirport"); ?></td>
              </tr>
            <?php endforeach; ?>
            
             <?php foreach($requestToAirport as $r): ?>
              <tr id="<?php echo $r['id']; ?>">
                <td><?php echo $this->showdate($r['departure_date']); ?> </td>
                <td><?php echo $r['city']; ?></td>
                <td><?php echo $r['iata']; ?></td>
                <td>Passenger</td>
                <td>$<?php echo $r['cost']; ?></td>
                <td><a onclick="getUsers('<?php echo $this->showmembers("passenger", $r['departure_date']); ?>');" href="javascript:void(0)">Click to View</a></td>
                <td><?php echo $this->showedit($r, "requests", "toAirport"); ?></td>
                <td><?php echo $this->showdelete($r, "requests", "toAirport"); ?></td>
               </tr>
            <?php endforeach; ?>
            
             <?php foreach($ridesBookedToAirport as $r): ?>
              <tr id="<?php echo $r['id']; ?>">
                <td><?php echo $this->showdate($r['departure_date']); ?> </td>
                <td><?php echo $r['city']; ?></td>
                <td><?php echo $r['iata']; ?></td>
                <td>Passenger</td>
                <td>$<?php echo $r['cost']; ?></td>
                <td><a href="javascript:void(0)" onclick="getUsers('<?php echo $this->showmembers("passenger", $r['departure_date']); ?>');">Click to View</a></td>
                <td>Only the driver can edit</td>
                <td>You can't delete a booking made</td>
               </tr>
            <?php endforeach; ?>
            
            
                
             <?php foreach($ridesBookedFromAirport as $r): ?>
              <tr id="<?php echo $r['id']; ?>">
                <td><?php echo $this->showdate($r['departure_date']); ?> </td>
                <td><?php echo $r['iata']; ?></td>
                <td><?php echo $r['city']; ?></td>
                <td>Passenger</td>
                <td>$<?php echo $r['cost']; ?></td>
                <td><a onclick="getUsers('<?php echo $this->showmembers("passenger", $r['departure_date']); ?>');" href="javascript:void(0)">Click to View</a></td>
                <td>Only the driver can edit</td>
                <td>You can't delete a booking made</td>
               </tr>
            <?php endforeach; ?>
            
            
                
             <?php foreach($requestsToAirportResponded as $r): ?>
              <tr id="<?php echo $r['id']; ?>">
                <td><?php echo $this->showdate($r['departure_date']); ?> </td>
                <td><?php echo $r['city']; ?></td>
                <td><?php echo $r['iata']; ?></td>
                <td>Driver</td>
                <td>$<?php echo $r['cost']; ?></td>
                <td><a onclick="getUsers('<?php echo $this->showmembers("driver", $r['departure_date']); ?>');" href="javascript(0)">Click to View</a></td>
                <td></td>
                <td></td>
               </tr>
            <?php endforeach; ?>
            
             <?php foreach($requestsFromAirportResponded as $r): ?>
              <tr id="<?php echo $r['id']; ?>">
                <td><?php echo $this->showdate($r['departure_date']); ?> </td>
                <td><?php echo $r['iata']; ?></td>
                <td><?php echo $r['city']; ?></td>
                <td>Driver</td>
                <td>$<?php echo $r['cost']; ?></td>
                <td><a onclick="getUsers('<?php echo $this->showmembers("driver", $r['departure_date']); ?>');" href="javascript:void(0)">Click to View</a></td>
                <td></td>
                <td></td>
               </tr>
            <?php endforeach; ?>
            </tbody>

          </table>
<?php endif; ?>
<div id="userlist">
    
</div>
<script>
$(document).ready(function(){
    $("#rides").dataTable();
})
</script>