<div class="rides_section tabing" style="display:true">
          <table border="0" cellspacing="0" cellpadding="5">
            <thead>
              <tr>
                <td class="width">DATE</td>
                <td class="width">FROM</td>
                <td class="width">TO</td>
                <td class="width">STATUS</td>
                <td class="width">COST</td>
                <td class="width">WHO WITH</td>
                <td class="width">XXXXX </td>
                <td class="width">XXXXX </td>
                <td class="width">XXXXX </td>
              </tr>
            </thead>
            <div id="ride_records">
            <?php 
            $fromAirport = $this->myrides[0]['ridesfromairport'];
            $toAirport = $this->myrides[1]['ridestoairport'];
            $requestToAirport = $this->myrides[2]['requestsfromairport'];
            $requestFromAirport = $this->myrides[3]['requeststoairport'];
            ?>
            
             <?php foreach($fromAirport as $ridefromairport): ?>
            <tbody>
              <tr>
                <td><?php echo $ridefromairport['departure_date']; ?> </td>
                <td><?php echo $ridefromairport['iata']; ?></td>
                <td><?php echo $ridefromairport['city']; ?></td>
                <td>Driver</td>
                <td><?php echo $ridefromairport['cost']; ?></td>
                <td>Carl T. <br>
                  Tom Z.</td>
                <td>&nbsp;</td>
                <td>&nbsp;</td>
                <td>&nbsp;</td>
              </tr>
            </tbody>
            <?php endforeach; ?>
            
            <?php foreach($toAirport as $ridetoairport): ?>
            <tbody>
              <tr>
                <td><?php echo $ridetoairport['departure_date']; ?> </td>
                <td><?php echo $ridetoairport['city']; ?></td>
                <td><?php echo $ridetoairport['iata']; ?></td>
                <td>Driver</td>
                <td><?php echo $ridetoairport['cost']; ?></td>
                <td>Carl T. <br>
                  Tom Z.</td>
                <td>&nbsp;</td>
                <td>&nbsp;</td>
                <td>&nbsp;</td>
              </tr>
            </tbody>
            <?php endforeach; ?>
            
             <?php foreach($requestToAirport as $ridetoairport): ?>
            <tbody>
              <tr>
                <td><?php echo $ridetoairport['departure_date']; ?> </td>
                <td><?php echo $ridetoairport['city']; ?></td>
                <td><?php echo $ridetoairport['iata']; ?></td>
                <td>Passenger</td>
                <td><?php echo $ridetoairport['cost']; ?></td>
                <td>Carl T. <br>
                  Tom Z.</td>
                <td>&nbsp;</td>
                <td>&nbsp;</td>
                <td>&nbsp;</td>
              </tr>
            </tbody>
            <?php endforeach; ?>
            
            <?php foreach($requestFromAirport as $ridetoairport): ?>
            <tbody>
              <tr>
                <td><?php echo $ridetoairport['departure_date']; ?> </td>
                <td><?php echo $ridetoairport['iata']; ?></td>
                <td><?php echo $ridetoairport['city']; ?></td>
                <td>Passenger</td>
                <td><?php echo $ridetoairport['cost']; ?></td>
                <td>Carl T. <br>
                  Tom Z.</td>
                <td>&nbsp;</td>
                <td>&nbsp;</td>
                <td>&nbsp;</td>
              </tr>
            </tbody>
            <?php endforeach; ?>
            
              <?php foreach($requestToAirport as $ridetoairport): ?>
            <tbody>
              <tr>
                <td><?php echo $ridetoairport['departure_date']; ?> </td>
                <td><?php echo $ridetoairport['city']; ?></td>
                <td><?php echo $ridetoairport['iata']; ?></td>
                <td>Passenger</td>
                <td><?php echo $ridetoairport['cost']; ?></td>
                <td>Carl T. <br>
                  Tom Z.</td>
                <td>&nbsp;</td>
                <td>&nbsp;</td>
                <td>&nbsp;</td>
              </tr>
            </tbody>
            <?php endforeach; ?>
            
            
            </div>
          </table>
        </div>
