<?php  $this->headTitle('FAQs');
?>
<section id="body_container">
    <!-- about_container starts -->
    <section id="about_container">
      <div class="about_heading">
        <h3>FAQs</h3>
      </div>
      <!-- about details starts -->
      <section class="about_details">
        <section class="howitworks_container">

            <h3>What is Rideorama?</h3>
            <h4>
                Rideorama is a ridesharing community focused on airports. We match drivers going to and from the airport with passengers.  That way, drivers can offset their costs and passengers get cheap rides.
            </h4>
            
           <h3>How do I book a ride?</h3>
           <h4>
           It’s free and easy to sign up for Rideorama.  
           The easiest way to sign up for Rideorama is through Facebook.  Click “Connect with Facebook” on our <a href="account/user/login">Sign In</a> page and you’re done! 
           If you don’t have a Facebook account you can still sign up using your email address. 
           </h4>
           
           <h3> I need a ride to the airport, how can Rideorama help me?</h3>
           <h4>You can “Post a Ride Request” on Rideorama and we’ll send you an email when a driver wants to offer you a seat.
             You can also search for drivers and see who is going to the airport when you need to get there. 
              Check the <a href="howitworks">How It Works Page for more information</a>. </h4>


           <h3> I am driving to the airport and I have couple of empty seats in my car, how can I offer a ride on Rideorama? </h3>
           
           <h4>You can “Post a ride offer” on Rideorama and we’ll send you an email 
               when a passenger wants to purchase a seat in your car.  
             You can also search Rideorama for passengers and see who needs a ride when you want to leave.  
             Check the <a href="howitworks">How It Works Page for more information</a>. </h4>

           <h3> How much does it cost to get a ride to the airport? </h3>
           <h4>Rideorama does not set any prices, ridesharers do. 
            Passengers set how much they are willing to pay by posting ride requests to Rideorama.  
            Drivers set how much seats cost in their cars by posting ride offers to Rideorama. </h4>

           <h3>Who can post on Rideorama?</h3>
           <h4>Any driver that has a valid drivers license, insurance, and is over 18 can offer seats using Rideorama.
               Any passenger that is over 18 can request seats using Rideorama.</h4>
 
           <h3>Are there any liability or insurance issues I need to be aware of: </h3>
           <h4>Most auto insurance policies also cover passengers in carpools as well.
               However, insurance policies vary and it is worth checking with your insurance agent.</h4>

           <h3>How do I decide who to ride with?</h3>
           <h4>Ridesharers provide information about themselves using their profiles.
             Review the pictures of the ridesharers, pictures of their cars, price of the trip, and detailed trip message ridesharers leave in their profile. 
             You have no obligation to ride with someone you are uncomfortable with.  
           </h4>
        
           <h3>Can I cancel my booking after paying for a seat?</h3>
           <h4>If you need to cancel your ride, please contact us at 720-443-3963 and we will help you. </h4>
          
           <h3>What happens if my driver does not show up?</h3>
           <h4>No worries, reach out to the Rideorama team at 720-443-3963 and we will make sure you get to the airport on time.</h4>
                 
           <h3>How do I get hold of you ?</h3>
           <h4>You can get in contact with the Rideorama team in three ways.  You can chat with us live using the app at the bottom of the page.  You can email us at team@rideorama.com.  And you can call us at 720-443-3963.
           </h4>

<div class="curve"><img src="<?php echo $this->baseUrl(); ?>/img/about_b_curv.png" alt=""/></div>
      <!-- about_container ends -->
    </section>
  </section>
    </section>
</section>