<script>

function testing(){
    $("#content").append("Just testing");
}
</script>
<?php

echo $this->number;
echo "<p></p>";
echo $this->twice;
echo $this->ajaxLink("Distance from my house to McDonalds",
                    "show/calc",
                    array('update' => '#content',
                        'beforeSend' => 'slideup',
                        'complete' =>  'testing()'
                        
                        ));