
<?php
    $this->title = "View all Cities";
    $this->headTitle($this->title);
?>
<br /><br />
<div id="view-content">
<p><a href="<?php echo $this->url(array('module'=> 'admin', 'controller'=>'city', 
        'action'=>'add-city'));?>">Add a new city</a></p>
<table>
<tr>
    <th>City</th>
    <th>State</th>
    <th>&nbsp;</th>
</tr>
<?php foreach($this->cities as $city) : ?>
<tr>
    <td><?php echo $this->escape($city->name);?></td>
    <td><?php echo $this->escape($city->state->name);?></td>
    <td>
        <a href="<?php echo $this->url(array('module' => 'admin', 'controller'=>'city', 
            'action'=>'edit-city', 'id'=>$city->id));?>">Edit</a>
        <a href="<?php echo $this->url(array('module' => 'admin', 'controller'=>'city', 
            'action'=>'delete-city', 'id'=>$city->id));?>">Delete</a>
        
      
    </td>
</tr>
<?php endforeach; ?>
</table>

</div>